### ISSUE TITLE
Filter checks on request URI equality

### ISSUE THREAD

**Issue by martinvisser** [TomCools/rickroll-security-spring-boot-starter#2]
I love this feature, but it lacks a bit of flexibility I think.

To avoid having too many path values to check for equality it would be nice if the filter uses a path matcher to see if the request URI matches a configured path.

I get some requests on my site which I would like to rickroll like these:
- /shop/wp-includes/wlwmanifest.xml
- /site/wp-includes/wlwmanifest.xml
- /sito/wp-includes/wlwmanifest.xml
- /2018/wp-includes/wlwmanifest.xml
- /2019/wp-includes/wlwmanifest.xml

I don't want to filter on extension `.xml`, but I do want to rickroll these request. So it would be nice if `/**/wp-includes/**` would be an option. I believe it could just extend on the current functionality, because an `AntPathMatcher` would still work like an equals check too.

I'm willing to create a PR myself.

**Comment by TomCools** [comment]
Hi Martin, 

Glad to hear you like this project 😊

Your addition sounds good! You can make the PR and we can discus in there if you want. I'll have a look at it this weekend. 😊

**Comment by TomCools** [comment]
Merged, updated, released in 1.3.0. Thanks for the contribution!
